name:         pg_dumpbinary
version:      2.13
version_from: pg_dumpbinary
installdirs:  site
recommends:
    Time::HiRes:                     0

distribution_type: script
generated_by: ExtUtils::MakeMaker version 6.17
